### ISSUE TITLE
Deserialise bitlists accepts sequences of bytes ending with 0x00

### ISSUE THREAD

**Issue by franck44** [ethereum/py-ssz#109]
Deserialise for bitlists
https://github.com/ethereum/py-ssz/blob/651471374ce57627fa4645c6b3e997858794122f/ssz/sedes/bitlist.py#L58

accepts input ending with 0-byte i.e. sequences of bytes ending with 0x00.

The following two tests:
```
(16, b"\x00", tuple()), # should not be accepted as last byte should be >= 1
(8, b"\xff\x00", (True,) * 7 ), # should not be accepted ...
```
can be added to the test cases (link below) to witness this behaviour.
https://github.com/ethereum/py-ssz/blob/651471374ce57627fa4645c6b3e997858794122f/tests/sedes/test_bitlist_serializer.py#L24

Seems to be a bug as it is impossible to serialise a bitlist into a sequence of bytes ending with 0x00 (a 1-bit is added before serialisation to a bitlist).
So the last byte of any serialised bitlists will be non-zero.

**Comment by franck44** [comment]
@jannikluhn @hwwhww This issue does not seem to get any follow-up and was created 6 weeks ago.

**Comment by pipermerriam** [comment]
Thanks for opening this.  Would you be willing to open a PR adding the suggested tests?

**Comment by franck44** [comment]
@pipermerriam yes will do.

**Comment by pipermerriam** [comment]
Hrm, upon more detailed inspection, I'm questioning whether this should be disallowed or not.  Is this strictly forbidden by the SSZ spec?  If so this is a no-brainer and we can add the proposed tests.  Otherwise, I would lean towards updating the main SSZ spec to explicitly disallow this before enforcing it here in `py-ssz`

**Comment by pipermerriam** [comment]
A brief look at https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#bitlistn suggests that we should indeed disallowed this.  Yes, please open the PR.

**Comment by franck44** [comment]
Any serialised version of a bit list ends with non 0-byte. So it is similar to deserialising a uint64 into uint8, that should not be allowed, correct?
This is not in the specs but the specs are incomplete. 
We are working on a [formal specification and verification](https://github.com/PegaSysEng/eth2.0-dafny) of the specs and this finding is part of it.

**Comment by franck44** [comment]
This part of the `deserialise` section of the specs seems to indicate there is room for improvement:

> Note that deserialization requires hardening against invalid inputs. A non-exhaustive list:

> Offsets: out of order, out of range, mismatching minimum element size.
> Scope: Extra unused bytes, not aligned with element size.
> More elements than a list limit allows. Part of enforcing consensus.

Making sure the deserialise `o` applies only to an object `o` that could have been serialised may fall into the category of `hardening the constraints on the inout values`.

**Comment by ralexstokes** [comment]
just to add some more color here, my understanding of the intention of the `ssz` spec is to have unique serializations/deserializations for a given object so any trailing null bytes should be rejected when deserializing... thanks for pointing this out on bitlist @franck44 !

**Comment by ralexstokes** [comment]
sorry did not mean to close

**Comment by franck44** [comment]
@ralexstokes @pipermerriam 
I created a PR related to this issue.

**Comment by franck44** [comment]
@pipermerriam We may close this issue now as the corresponding PR has been merged.
