### ISSUE TITLE
An empty bitvector is illegal

### ISSUE THREAD

**Issue by booleanfunction** [ethereum/py-ssz#111]
In the [eth2.0-specs](https://github.com/ethereum/eth2.0-specs) it specifies within [simple-serialise.md](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md) (Illegal types section) reads:

> Empty vector types (Vector[type, 0], Bitvector[0]) are illegal.

However in bitvector.py an error is raised only if `bit_count` is negative. An error should be raised if `bit_count` <= 0.

https://github.com/ethereum/py-ssz/blob/651471374ce57627fa4645c6b3e997858794122f/ssz/sedes/bitvector.py#L19-L22

This can be contrast to vector.py where the error is correctly raised if `length` <= 0.

https://github.com/ethereum/py-ssz/blob/651471374ce57627fa4645c6b3e997858794122f/ssz/sedes/vector.py#L30-L32

**Comment by pipermerriam** [comment]
If you'd like to open a pull request fixing this discrepancy I'd be happy to get it reviewed and merged.

**Comment by carver** [comment]
Closed by #112
