### ISSUE TITLE
Discussion: rename `List`?

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-ssz#12]
Per https://github.com/ethereum/py-ssz/pull/10#issuecomment-447340112
The `List` sedes returns `Tuple`, should we rename `List` to `Array` or `OrderedCollection` or another name?

- Pros:
    * It will be easier to understand the returning result is *not* python `list`.
- Cons:
    * Our preference to another name instead of `List` is in the context of Python language, and then our implementation will not align with [the spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/simple-serialize.md#listvectors).
    * But if the new name is much better than `List` (regarding to describing the behavior of this kind of data type), we can also add a proposal on [ethereum/eth2.0-specs](https://github.com/ethereum/eth2.0-specs).

**Comment by jannikluhn** [comment]
I'm in favor of `List` as we have type annotations for the return type and staying aligned with the spec and other implementations seems more important.

If we want to rename it though, `Vector` would be another option as it's used as a synonym in the spec a couple of times.

**Comment by hwwhww** [comment]
@jannikluhn 
It just came to my mind that there's a naming conflict of `typing.List` and `ssz.sedes.List`.

**Comment by jannikluhn** [comment]
We've decided to not rename `List` as the basic sedes classes will in practice only be used in very isolated places. In case of possible ambiguities, don't import `List` directly but use `ssz.List` or `sedes.List`.
