### ISSUE TITLE
Implement containers

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-ssz#14]
Implement serialization and deserialization of SSZ containers as specified [here](https://github.com/ethereum/eth2.0-specs/blob/master/specs/simple-serialize.md#container).

The API should be similar to `pyrlp`. In particular, there should be a class `ssz.Serializable` that can be subclassed to define SSZ containers. Subclasses have a `fields` attribute that defines their internal structure (see [this class](https://github.com/ethereum/py-evm/blob/master/eth/beacon/types/attestations.py#L21) for an example). `ssz.Serializable` classes are sedes objects for their instances, so they should define `serialize` and `deserialize` classmethods. Field values are initialized using the `__init__` constructor that checks that all, but no additional arguments are given. Field values can be accessed as read only properties. The code should be well tested.

I suspect that pretty much all of this except for the implementation of `serialize` and `deserialize` can be copied from `pyrlp`. The `Changeset` functionality is optional.

**Comment by Bhargavasomu** [comment]
On this.

**Comment by Bhargavasomu** [comment]
@jannikluhn I have observed that the `serializable` class in `pyrlp` has a lot of functions like `__hash__`, and `__iter__`. I don't gues such functions are required here right?

**Comment by Bhargavasomu** [comment]
@hwwhww @jannikluhn I have gone through the specs of `container` and while doing the implementation, I have observed that there is no need for `sorting` the `fields`. Please confirm this.

**Comment by hwwhww** [comment]
> I have observed that there is no need for sorting the fields. 

Can you elaborate more?
Do you mean any incompatibility to [the spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/simple-serialize.md#container) - "To serialize a container, obtain the set of its field's names and sort them lexicographically"?

**Comment by Bhargavasomu** [comment]
@hwwhww yes, the same `serialization/deserialization` process would work the same with and without sorting, as the `metaclass` stores them in the order given by the user (need not be sorted order). And finally the same sorted order can be used for `deserialization` also. So in `contrast` to the `spec`, I don't see the use and need for `sorting`.

That said, please correct me if I am missing something.

**Comment by jannikluhn** [comment]
> @jannikluhn I have observed that the serializable class in pyrlp has a lot of functions like __hash__, and __iter__. I don't gues such functions are required here right?

As far as I can see we only need `__eq__`, `__copy__`, and `__deepcopy`. `__hash__` is used for implementing `__eq__`, so it's probably a good idea to use that one too (even though I don't think the caching is necessary). `__iter__`, `__getitem__` and `__len__` seem to exist to allow list- and dict-like access which I don't see a good reason for.


> @hwwhww yes, the same serialization/deserialization process would work the same with and without sorting, as the metaclass stores them in the order given by the user (need not be sorted order). And finally the same sorted order can be used for deserialization also. So in contrast to the spec, I don't see the use and need for sorting.

No, we need to follow the spec. Otherwise we aren't interoperable with other implementations.

That said, there's [some discussion](https://github.com/ethereum/eth2.0-specs/issues/275) around field ordering. But as long as we haven't agreed on a change and the spec hasn't been updated, we need to follow the current version.

**Comment by hwwhww** [comment]
The spec has been updated! 😄https://github.com/ethereum/eth2.0-specs/pull/339

**Comment by hwwhww** [comment]
closing in favor of #17
