### ISSUE TITLE
Benchmark: v.s. old implementation

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-ssz#21]
## What was wrong?
I wonder how much improvement we got. 😃 (or not?)

## How can it be fixed?

- Edit `ethereum/beacon_chain/ssz/`
    - Apply https://github.com/ethereum/beacon_chain/pull/134/files and the latest spec
    - Apply Keccak-256 hash
- Run `time_test.py`: https://github.com/ethereum/beacon_chain/blob/master/time_test.py
- v.s. the current `py-ssz` implementation

**Comment by ChihChengLiang** [comment]
After fixing diff in two algorithms:
```
$ python time_test.py
Old hash_ssz: 14.037278175354004
b"\xb7\x83:.\x11*\x19\xad\r\x94\xf3\xa1\xcd'S\xeb\x19\xe4X\xd76wJ\xc6\x89\x91\xf98\x99\x03[\xa7"
New hash_tree_root 14.739357948303223
b"\xb7\x83:.\x11*\x19\xad\r\x94\xf3\xa1\xcd'S\xeb\x19\xe4X\xd76wJ\xc6\x89\x91\xf98\x99\x03[\xa7"
```

old ssz: https://github.com/ethereum/beacon_chain/compare/master...ChihChengLiang:time_test?expand=1
new ssz: https://github.com/ethereum/py-ssz/compare/master...ChihChengLiang:time_test?expand=1#diff-e1f1b447c1c4d61a32e846568f901c8e

**Comment by ChihChengLiang** [comment]
The benchmark of implementation now reflected in #24
