### ISSUE TITLE
Support container type for tree hashing

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/py-ssz#23]
## What was wrong?

Tree Hash should be able to hash container types.

## How can it be fixed?

- The implementation should look like this: https://github.com/ethereum/py-ssz/compare/master...ChihChengLiang:time_test?expand=1#diff-e1f1b447c1c4d61a32e846568f901c8e
- Address this issue when #17 is merged

**Comment by hwwhww** [comment]
@ChihChengLiang #17 is merged.
