### ISSUE TITLE
Import/Export to json or yaml

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/py-ssz#65]
## What was wrong?

#60 provides basic functionality to import/export a `Serializable` from/to a json/yaml file, but it looks like there are rooms for improvement. Here are some examples:

- Provide `to_json(self)` and `to_yaml(self)` methods to `Serializable`
- The import/export should be tools and utilities, but the relevant methods are touching the core classes. Maybe need a way to separate them.
- Should be able to customize the output of Uints to digits or hex to support different use cases.

## How can it be fixed?

Requires discussion

**Comment by jannikluhn** [comment]
- Conceptually this has nothing to do with SSZ encoding or decoding, so I think the various sedes objects shouldn't have to deal with this. Fortunately, the logic there is quite minimal (just `encode_hex`/`decode_hex` as far as I can see) so it shouldn't be too hard to move it elsewhere. Maybe this could just be a function that takes only the value and checks via `isinstance` how to format it -- no need to even know the sedes object.

- Do we actually need JSON or YAML or would just plain Python dicts (with human readable contents) be sufficient? I think this would simplify the API a little (no need for both `to/from_json/yaml`, just one `to/from_formatted_dict` or something similar). And the step to actual JSON/YAML is quite a short one (`json.dumps(formatted_dict)`).

- Do we want to format only `Serializable`s or everything SSZ encodable? If the first is enough we could simplify the API (just a method in `Serializable`, no need for an extra library module), but we won't be able to serialize lists and vectors and strings and ints with the same function.
