### ISSUE TITLE
Avoid collisions on `root` property?

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/py-ssz#79]
# What is wrong?

If a class inherits from one of our ssz types, then it gets a `root` property that caches the `hash_tree_root` computation.

There is a collision that occurs if this class has another property or even an `ssz` field w/ the name `root`.

This collision caused a bug w/ our `__eq__` instance which compares the `root` property to determine equivalence.

# How to fix it?

If we are just concerned about fixing the `__eq__` instance, then we can try this to modify the property/method resolution order:

```python
  def __eq__(self, other):
        satisfies_class_relationship = (
            issubclass(self.__class__, other.__class__) or
            issubclass(other.__class__, self.__class__)
        )

        if not satisfies_class_relationship:
            return False
        else:
            # current solution:
            # return self.root == super.root
            return super(self.__class__, self).root == super(other.__class__, other).root
```

This seems to avoid the "leaf" `root` property (defined directly on our child class) and instead searches in any of the parent classes for a `root` property -- which then defers to the `hash_tree_root` definition we want.

**Comment by ralexstokes** [comment]
Another option here is to just change the definition in this library to `hash_tree_root` (instead of just `root`).

It should generally avoid naming collisions and just means the call site gets a bit longer, i.e. `a.root ~> a.hash_tree_root` but this isn't a big deal

**Comment by pipermerriam** [comment]
I'm preferential to the rename approach.  Less complexity.  Less surprising.

**Comment by carver** [comment]
Rename seems reasonable to me. :+1: 

Another question to ask is whether the subclasses really needed to be subclasses. Maybe they should be an independent class that uses the SSZ class as a subcomponent. If the rename is insufficient, I can help brainstorm alternatives. (I would just want a link to the current subclass, first)

**Comment by hwwhww** [comment]
I'm in favor of renaming; it also helps distinguish between `signing_root` and `hash_tree_root` a little bit.

**Comment by ralexstokes** [comment]
@carver yeah that is a good question and points towards a possible refactoring of this -- it seems that we are embedded enough in the subclassing way of doing things atm that it doesn't seem worthwhile to make a change that big when we can just rename the property and that _should_ be good enough ;)

**Comment by cburgdorf** [comment]
I'm in favor of renaming as well. I also like @carver idea of embedding rather than subclassing (I *think* that is basically Go's approach to inheritance with some added syntax sugar) but renaming seems like the obvious easy answer for a quick resolution.
