### ISSUE TITLE
Introduce abstract base class for sedes objects

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-ssz#9]
We currently check if an object is a `sedes` by checking if it has both a `serialize` and a `deserialize` method: https://github.com/ethereum/py-ssz/blob/master/ssz/utils.py#L12

This is ugly and can in theory lead to bugs if a wrong object with the same interface is used (e.g. an RLP sedes).

As [suggested](https://github.com/ethereum/py-ssz/pull/3#discussion_r238741262) by @pipermerriam, we could instead use an abstract base class and replace the `hasattr` checks with `isinstance` checks against it. Then we could also get rid of the `is_sedes` function altogether as `isinstance(sedes, BaseSedes)` would be equally clear.

**Comment by ChihChengLiang** [comment]
work on this

**Comment by ChihChengLiang** [comment]
Question: Do we need to add a new abstract class for list_sedes, say List and Bytes?
