### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-ssz#93]
Should we use black in py-ssz? In my opinion it would make sense, even if it's just for the sake of consistency with the other eth2 packages (`eth2` and `py-libp2p`).

cc @hwwhww @ralexstokes @pipermerriam

**Comment by pipermerriam** [comment]
I'm in favor

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ralexstokes** [comment]
i'm also in favor, for the record ;)
